{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "travel.fullname" . }}-postgres-secret
type: Opaque
data:
  postgres-password: {{ .Values.postgres.postgresPassword | b64enc }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "travel.fullname" . }}-postgres
spec:
  serviceName: {{ include "travel.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "travel.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "travel.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.postgresDatabase }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.postgresUser }}"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "travel.fullname" . }}-postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "travel.fullname" . }}-postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: {{ include "travel.fullname" . }}-postgres
---
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}
{{- end }}
